version: "3.1"

services:
  postgres:
    image: postgres:10
    container_name: hbfdb_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hbfdb_user
      - POSTGRES_PASSWORD=hbfdb_password
      - POSTGRES_DB=hbfdb_db